name: Release Workflow

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t pro-stat-lol:${{ github.sha }} .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name test-container pro-stat-lol:${{ github.sha }}
          sleep 10
          curl -f http://localhost:8000 || (echo "Tests failed" && exit 1)

      - name: Clean up Docker container
        run: |
          docker stop test-container
          docker rm test-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag pro-stat-lol:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/pro-stat-lol:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/pro-stat-lol:${{ github.sha }}